### ISSUE TITLE
List of implementations

### ISSUE THREAD

**Issue by nichtich** [obsidianmd/jsoncanvas#11]
The page https://jsoncanvas.org/ should list known implementations. I guess by know it's 

- [Obsidian](https://obsidian.md/) 
- [unnamed reference implementation used in this repository](https://github.com/obsidianmd/jsoncanvas/blob/main/assets/canvas.js)
- ...?

People should be encouraged to use the format in other software as well.

**Comment by julienduroure** [comment]
I just publish a quick implementation in Rust: https://crates.io/crates/jsoncanvas

**Comment by kepano** [comment]
The list can be found at https://jsoncanvas.org/docs/apps

See [/docs/apps.md](https://github.com/obsidianmd/jsoncanvas/blob/main/docs/apps.md)
