### ISSUE TITLE
What is the purpose of the numerical color values?

### ISSUE THREAD

**Issue by clbarnes** [obsidianmd/jsoncanvas#37]
The spec states that the color field expects a string. Does that mean that preset colors should be given as e.g. `"red"`? If so, what is the need for the numbers they each map to?

**Comment by kepano** [comment]
This is explained in the spec. The preset colors exist so that applications can use color values that match their brand or color scheme, i.e. different apps may have a different default red

> Specific values for the preset colors are intentionally not defined so that applications can tailor the presets to their specific brand colors or color scheme.

**Comment by clbarnes** [comment]
Sorry if there was misunderstanding - this question is not about the value of *preset colors*. It is, as stated in the question, about *numerical values* for those presets. What is the purpose of the **numbers** associated with  those presets? The spec says that the field expects a string. So is the correct thing to do to specify `"red"`? In what way, then, is the preset red associated with the number 1?

**Comment by kepano** [comment]
You can see an example in the [sample](https://github.com/obsidianmd/jsoncanvas/blob/main/sample.canvas#L4)

`"color":"6"`

**Comment by clbarnes** [comment]
OK - can this be un-marked as completed until the spec clarifies that?

**Comment by kepano** [comment]
The spec currently states that colors are strings and that there are six numbered presets. Do you have a suggestion about how to make this more clear?

**Comment by clbarnes** [comment]
For maximum informative-ness, maybe something like

> Color values MUST be represented by strings. The string MAY represent either be RGB values encoded as an octothorpe followed by 3 upper-cased hexadecimal pairs (e.g. `"#FF0000"`), or an integer representing a preset color according to the table below (e.g. `"1"`). The exact color of each preset is left up to implementors, who MAY apply their own color scheme.

but my understanding would have been helped greatly simply by including the double quotes in the values in the table, like

```markdown
- `"1"` red
- `"2"` orange
...
```
