### ISSUE TITLE
Doc: add link to sourcecode

### ISSUE THREAD

**Issue by linonetwo** [obsidianmd/jsoncanvas#39]
Seems this repo is only a spec without code. To make this really useful, we need link to the npm package or github repo with useable code.

For example, the infinite canvas library https://github.com/tldraw/tldraw opensource both the spec and the source code.

**Comment by kepano** [comment]
Libraries are linked to from [docs/apps.md](https://github.com/obsidianmd/jsoncanvas/blob/main/docs/apps.md)
