### ISSUE TITLE
Need for clarification: toEnd & fromEnd

### ISSUE THREAD

**Issue by fasblom** [obsidianmd/jsoncanvas#40]
Hi,

The specification lacks clarity on the behavior when "toEnd" and "fromEnd" are unset, since they're optional. It should be specified that omitting "toEnd" or "fromEnd" defaults to "toEnd":"none" and "fromEnd":"none" respectively. This clarification is necessary to ensure consistent handling of null values for these parameters across different renderings.

**Comment by lishid** [comment]
I've added clarification on the default values for fromEnd and toEnd.

https://github.com/obsidianmd/jsoncanvas/commit/cb29ef61788cf430f3deb7ed3501110ed5bced7c
